/**
 * Per-city facts used to assemble the Lower Mainland fencing guides.
 * Each city gets a ~2000-word post via city-post.ts. The unique paragraphs,
 * neighbourhoods, bylaw notes, and FAQ answers here are what make each
 * post distinct for search and LLM ingestion.
 */
export interface CityFact {
  /** URL-safe slug. Post URL becomes /blog/fencing-in-{slug}. */
  slug: string;
  name: string;
  region: "Metro Vancouver" | "Fraser Valley";
  postalPrefix: string;
  climate: string;
  terrain: string;
  neighbourhoods: string[];
  commonProjects: string[];
  bylawHeight: string;
  bylawSummary: string;
  bylawUrl: string;
  bylawUrlLabel: string;
  materialNotes: string;
  /** Two ~130-word hand-written paragraphs unique to this city. */
  uniqueParagraphs: [string, string];
  costNote: string;
  faq: Array<{ q: string; a: string }>;
  ogImage: string;
}

const OG = {
  best: "/og/blog-best-fencing-options.jpg",
  wood: "/og/blog-chain-link-vs-wood.jpg",
  why: "/og/blog-why-consider-fencing.jpg",
  gates: "/og/blog-barrier-gates.jpg",
};

export const CITIES: CityFact[] = [
  {
    slug: "vancouver",
    name: "Vancouver",
    region: "Metro Vancouver",
    postalPrefix: "V5 / V6",
    climate: "Vancouver sits in a coastal temperate rainforest — 1,150+ mm of rain a year, mild winters, and a marine salt load that eats cheap galvanizing.",
    terrain: "Lots range from steep-sloped Point Grey and Kitsilano hillsides to flat, high-water-table blocks in South Vancouver and the Grandview flats.",
    neighbourhoods: ["Kitsilano", "Point Grey", "Dunbar", "Kerrisdale", "Mount Pleasant", "East Van", "South Vancouver"],
    commonProjects: ["Rear-yard cedar privacy fences", "Black vinyl-coated chain link on lane sides", "Ornamental front-yard picket", "Strata perimeter replacements"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "The City of Vancouver regulates fence height under the Zoning and Development By-law. Fences do not require a building permit in most residential zones as long as they stay inside the standard height envelope, but corner lot sightline triangles are strictly enforced.",
    bylawUrl: "https://vancouver.ca/home-property-development/fences.aspx",
    bylawUrlLabel: "City of Vancouver — Fences page",
    materialNotes: "Vancouver's rain and marine salt push us toward hot-dip galvanized hardware and black vinyl-coated chain link on rear yards; cedar remains the front-yard default.",
    uniqueParagraphs: [
      "Vancouver's older housing stock — the century-old craftsman blocks through Kitsilano, Mount Pleasant, and Dunbar — is where fencing gets interesting. Lot lines don't always match what the fence has been for the last forty years, root systems from mature street trees stretch a straightforward post dig into an all-day job, and the neighbour's original 1970s post is often still buried in concrete two feet from the surveyed line. We start every Vancouver quote with a title search reference and, on contested lines, recommend a proper survey before the auger comes out. It costs a few hundred dollars and prevents the kind of dispute that ends in a bylaw complaint six months later.",
      "Density matters too. In neighbourhoods like Mount Pleasant, East Van, and South Vancouver, tight side-yard setbacks and detached laneway houses have pushed demand for tall, close-board cedar and horizontal-slat privacy fences that block sightlines from second-storey windows. We build a lot of 6-ft cedar with an extra 12-inch lattice or slat top-cap — which, once you include the trellis calculation, still sits inside Vancouver's height rules for most residential zones. On laneway-facing runs we default to black vinyl-coated chain link with privacy slats: it lasts twice as long as cedar in the constant lane-side moisture and doesn't get tagged.",
    ],
    costNote: "Vancouver labour and access fees run a touch above the Fraser Valley average, and permit-parking or restricted alley access on the West Side can add a day of setup on a tight urban lot.",
    faq: [
      { q: "Do I need a permit to build a fence in Vancouver?", a: "In most residential zones, no. Fences up to 1.83 m rear/side and 1.2 m front are allowed without a building permit under Vancouver's Zoning and Development By-law, but corner-lot sightline triangles and pool enclosures still apply." },
      { q: "How tall can a backyard fence be in Vancouver?", a: "1.83 m (6 ft) on the side and rear property lines in standard residential zones. Front-yard fences are capped at 1.2 m (4 ft). Retaining walls that push effective height above those limits can trigger a variance." },
      { q: "How much does a cedar fence cost in Vancouver?", a: "A standard 6 ft cedar privacy fence typically runs $55–$85 per linear foot installed in Vancouver. Horizontal-slat or clear-cedar upgrades run $85–$120 per linear foot. Gates and access-restricted West Side lots price separately." },
      { q: "Who is responsible for a shared fence between two Vancouver neighbours?", a: "By default, a fence on the exact property line is jointly owned. Best practice is a written agreement between neighbours before install; if only one owner wants the fence, it can be built entirely on that owner's side and remains solely theirs." },
      { q: "What's the best fence material for Vancouver's rainy climate?", a: "Hot-dip galvanized (or black vinyl-coated) chain link and Western red cedar both handle Vancouver's rain and marine salt well. Avoid pressure-treated fence boards — they cup and check faster than cedar in a coastal climate." },
    ],
    ogImage: OG.wood,
  },
  {
    slug: "burnaby",
    name: "Burnaby",
    region: "Metro Vancouver",
    postalPrefix: "V3J / V5A / V5B / V5C / V5E / V5G / V5H",
    climate: "Burnaby shares Vancouver's coastal rain pattern but sits slightly warmer inland — 1,100 mm of rain a year and less direct marine exposure than the West Side.",
    terrain: "Burnaby is defined by ridges — Burnaby Mountain in the north, Capitol Hill, and the Burnaby Heights bluff — with flat blocks through South Burnaby and along the Fraser.",
    neighbourhoods: ["Burnaby Heights", "Capitol Hill", "Brentwood", "Metrotown", "Edmonds", "Highgate", "South Slope"],
    commonProjects: ["Strata townhouse perimeters", "Cedar privacy on sloped lots", "Ornamental front-yard fences", "Commercial chain link for Big Bend industrial"],
    bylawHeight: "1.83 m rear/side, 1.22 m front",
    bylawSummary: "Burnaby regulates fences through Zoning Bylaw No. 4742. Standard height limits apply without a permit, and there are specific sightline rules at driveway and street intersections. Pool enclosures follow provincial building code.",
    bylawUrl: "https://www.burnaby.ca/services-and-payments/permits-and-applications/building-permits/fences",
    bylawUrlLabel: "City of Burnaby — Fence permits & regulations",
    materialNotes: "Burnaby's slope changes on lots along the ridges mean stepped fence design and longer posts — cedar boards work well because they can be trimmed to follow grade cleanly.",
    uniqueParagraphs: [
      "Burnaby's terrain is the story on almost every quote. Lots on the north slope of Burnaby Mountain, up through Capitol Hill and the Heights, drop several feet across the width of a standard yard. A racked-panel install — where cedar boards follow the grade at an angle — looks sloppy on a Burnaby slope; we step the fence in 4 or 6 foot sections instead, with the top and bottom of each section parallel to the ground and a small triangular gap at each step. Posts on the downhill side sit noticeably higher out of the ground, so we extend post depth accordingly rather than just using longer boards.",
      "South Burnaby and the Big Bend industrial area are the other half of our Burnaby work. Big Bend is one of the last remaining industrial pockets in Metro Vancouver, and the perimeter fencing spec there is different from residential — 8-foot galvanized chain link with a top rail, single or triple-strand barbed wire, and driveway gates sized for tractor-trailers. We also do a fair bit of Metrotown-area strata perimeter replacement, usually black vinyl-coated chain link because it disappears into the landscaping and satisfies the strata board's aesthetic requirements without the cost of ornamental steel.",
    ],
    costNote: "Burnaby is close to Vancouver on pricing. Sloped and stepped installs on the ridge neighbourhoods add roughly 10–15% over a flat-ground quote for the same linear footage.",
    faq: [
      { q: "Do I need a permit for a fence in Burnaby?", a: "No permit is required in Burnaby for fences that meet standard height limits (1.83 m rear/side, 1.22 m front). Anything taller requires a variance, and pool enclosures always follow BC Building Code." },
      { q: "How much does chain link fencing cost in Burnaby?", a: "Standard 6-ft galvanized chain link runs $32–$48 per linear foot installed in Burnaby. Black vinyl-coated is $42–$60 per linear foot. Sloped lots on Capitol Hill or Burnaby Mountain add about 10–15% for the extra post depth and stepping." },
      { q: "Can I build a fence on my sloped Burnaby lot?", a: "Yes. We step the fence in 4 or 6 foot sections to follow the grade cleanly rather than racking boards at an angle. Posts on the downhill side are set deeper to compensate." },
      { q: "What is Burnaby's setback requirement for fences?", a: "Fences can be built on the property line up to the standard height limit. Sightline triangles at driveway and street intersections require lower height — check the Burnaby Zoning Bylaw for the specific dimensions." },
      { q: "Do you install commercial fencing in the Big Bend industrial area?", a: "Yes. Big Bend is one of our regular commercial areas — we install 8-foot galvanized chain link, barbed wire, cantilever gates, and equipment enclosures for industrial and warehouse clients across Burnaby." },
    ],
    ogImage: OG.best,
  },
  {
    slug: "surrey",
    name: "Surrey",
    region: "Metro Vancouver",
    postalPrefix: "V3R / V3S / V3T / V3V / V3W / V3X / V4A / V4N / V4P",
    climate: "Surrey averages 1,200 mm of rain annually — slightly wetter than Vancouver — with more freeze-thaw cycles inland and higher summer heat in Cloverdale and South Surrey.",
    terrain: "Surrey covers everything from farmland in Cloverdale to flat suburban blocks in Fleetwood to hillside acreage in South Surrey and the Grandview Heights bluff.",
    neighbourhoods: ["Cloverdale", "Fleetwood", "Newton", "Guildford", "South Surrey", "Grandview Heights", "Whalley (City Centre)"],
    commonProjects: ["Acreage perimeter chain link", "Cedar privacy on new-build lots", "Farm and paddock fencing", "School and playground perimeters"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Surrey regulates fencing under Zoning Bylaw No. 12000. Fences within standard heights don't need a permit; agricultural and industrial zones have different allowances. Sightline triangles at intersections are enforced.",
    bylawUrl: "https://www.surrey.ca/services-payments/permits-licences-inspections/building-permits/fence-requirements",
    bylawUrlLabel: "City of Surrey — Fence requirements",
    materialNotes: "Surrey's larger lot sizes and agricultural zones drive higher volumes of long-run galvanized chain link and page-wire farm fencing than the more compact Metro Vancouver cities.",
    uniqueParagraphs: [
      "Surrey is one of our highest-volume markets and it's also one of the most varied. We'll finish an ornamental steel front-yard picket on a South Surrey Morgan Creek lot in the morning, then move a crew out to an ALR property in Cloverdale to run 400 feet of 5-foot page-wire farm fence in the afternoon. That range is exactly why we run our own excavation kit — the auger that handles a cedar-post backyard in Fleetwood isn't the right tool for setting fifty pressure-treated corner posts through a rocky Cloverdale field. Having the Kubota and the drill attachments on our own truck means we don't wait on a subcontractor and we don't compromise on post depth.",
      "New residential construction is the other constant in Surrey. Grandview Heights, Sunnyside, and the Clayton Heights developments have been pouring foundations for years, and every new home eventually needs a rear-yard and side-yard fence. Builder specs typically call for 6-foot cedar rear yards with a black vinyl-coated chain link side yard that keeps the sightline open into the neighbour's yard while still containing dogs and kids. We coordinate with the landscaper on grade and with the builder on lot-line survey pins before any post goes in, which is a small detail that prevents most of the neighbour-line disputes we see other contractors get pulled into.",
    ],
    costNote: "Surrey pricing is comparable to Langley and slightly below Vancouver. Long acreage runs earn a per-linear-foot discount at 500+ feet; short residential jobs on tight new-build lots price at the standard rate.",
    faq: [
      { q: "How tall can a fence be in Surrey without a permit?", a: "1.83 m (6 ft) on rear and side property lines, 1.2 m (4 ft) in the front yard. Agricultural (ALR) properties have different rules and can go taller for livestock containment. Pool enclosures follow BC Building Code." },
      { q: "How much does farm fencing cost in Surrey?", a: "Standard 5-ft page-wire farm fence with treated posts runs roughly $12–$22 per linear foot installed in Surrey, depending on terrain, post spacing, and gate count. Longer runs (500+ ft) earn a per-foot discount." },
      { q: "Do you install fencing for new construction in Grandview Heights and Clayton?", a: "Yes. Surrey new-builds are a large share of our residential work. We coordinate directly with builders and landscapers, work off surveyed lot pins, and can schedule the fence install right after grade is finished." },
      { q: "Can I build a fence on the ALR in Surrey?", a: "Yes, agricultural fencing (page wire, high-tensile, or standard chain link for livestock and equipment containment) is permitted on ALR land in Surrey without a residential-style height cap, though setback and sightline rules still apply." },
      { q: "What's the best fence for a Cloverdale acreage?", a: "For perimeter containment on rural Surrey acreages we usually recommend either 6-ft galvanized chain link (for security and equipment yards) or 5-ft page-wire on treated posts (for livestock and lower-cost long runs). Ornamental steel driveway gates and cattle guards round out the entry." },
    ],
    ogImage: OG.best,
  },
  {
    slug: "richmond",
    name: "Richmond",
    region: "Metro Vancouver",
    postalPrefix: "V6V / V6W / V6X / V6Y / V7A / V7B / V7C / V7E",
    climate: "Richmond is coastal and low-lying — 1,100 mm of rain, high water table year-round, and salt-laden marine air across most of the island.",
    terrain: "Richmond sits on the Fraser River delta at roughly 1 metre above sea level. Soil is soft alluvial clay and silt with the water table often within a few feet of the surface.",
    neighbourhoods: ["Steveston", "Terra Nova", "Seafair", "Broadmoor", "Riverdale", "Hamilton", "Ironwood"],
    commonProjects: ["Cedar privacy with elevated post depth", "Steveston waterfront ornamental", "Chain link for Ironwood industrial", "Pool-code compliant enclosures"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Richmond regulates fences under Zoning Bylaw No. 8500. Fences within standard height require no permit, but corner sightline triangles and setback distances from Richmond's extensive dyke and drainage ditch network are strictly applied.",
    bylawUrl: "https://www.richmond.ca/services/planning/buildingpermits/fenceretaining.htm",
    bylawUrlLabel: "City of Richmond — Fence & retaining wall information",
    materialNotes: "Richmond's soft delta soil and high water table mean every post has to be set deeper than a standard Fraser Valley spec — 36 in. minimum on residential, 42 in. on gates.",
    uniqueParagraphs: [
      "Nothing about fencing in Richmond is standard because nothing about the ground is. The entire island is Fraser River delta — soft, wet clay and silt sitting a metre above sea level, with a water table so shallow that most post holes fill with groundwater before the concrete goes in. On a Richmond quote we default to 36-inch post depth minimum, dry-mix bagged concrete tipped straight into the hole and hydrated by the groundwater, and hot-dip galvanized post hardware everywhere. Standard 30-inch post depth that would be fine in Cloverdale will fail in Steveston within five years — the post slowly walks its way out of the wet clay each freeze-thaw cycle.",
      "Steveston, Terra Nova, and Seafair also give us the salt-air problem. The onshore wind carries a constant fine load of marine salt that shreds any hardware that isn't hot-dip galvanized or stainless. Plain zinc-plated screws will bleed rust down a cedar board within two winters on a Steveston fence line. We spec stainless ring-shank nails or hot-dip galvanized screws on every Richmond cedar job, and we pass on the small material cost because the finish holds up for the life of the fence. Ironwood and the eastern industrial pockets are less brutal on hardware but the soft-soil rules still apply.",
    ],
    costNote: "Richmond quotes typically run 5–10% above a comparable Fraser Valley job for the deeper post depth, upgraded hardware, and — on some sites — permit paperwork for fences that back onto a dyke or drainage ditch right-of-way.",
    faq: [
      { q: "Why do fence posts in Richmond need to be set deeper?", a: "Richmond sits on soft Fraser River delta soil with a shallow water table. Standard 30-inch post depth will walk out of the ground within a few years. We set posts to 36 in. minimum on residential and 42 in. on gates to compensate." },
      { q: "Can I build a fence near a Richmond drainage ditch or dyke?", a: "Not always. Fences within the city's dyke or drainage right-of-way require approval. We pull the current setback requirements from the City of Richmond before quoting any fence that runs along or backs onto a ditch." },
      { q: "What hardware holds up in Steveston's salt air?", a: "Hot-dip galvanized or stainless steel — no exceptions. Plain zinc-plated screws will rust and bleed through cedar boards within two Steveston winters. We use hot-dip galvanized screws and stainless ring-shank nails on all coastal Richmond jobs." },
      { q: "Do I need a permit for a fence in Richmond?", a: "Not for a standard-height residential fence (1.83 m rear/side, 1.2 m front). Pool enclosures, corner sightline triangles, and any fence near a dyke or drainage ditch have additional requirements." },
      { q: "How much does a fence cost in Richmond?", a: "Roughly $60–$95 per linear foot for a 6-ft cedar privacy fence installed, $45–$65 for black vinyl-coated chain link — about 5–10% above the Fraser Valley average to cover deeper posts and upgraded hardware." },
    ],
    ogImage: OG.best,
  },
  {
    slug: "coquitlam",
    name: "Coquitlam",
    region: "Metro Vancouver",
    postalPrefix: "V3B / V3C / V3E / V3J / V3K",
    climate: "Coquitlam gets 1,700+ mm of rain a year — the wettest of the Tri-Cities — with more snow at elevation on Burke Mountain and Westwood Plateau.",
    terrain: "From flat riverfront in Maillardville up to the steep slopes of Burke Mountain and Westwood Plateau, Coquitlam has some of the widest grade variation in Metro Vancouver.",
    neighbourhoods: ["Burke Mountain", "Westwood Plateau", "Coquitlam Centre", "Maillardville", "Como Lake", "Ranch Park", "Eagle Ridge"],
    commonProjects: ["Cedar privacy on steep hillside lots", "Chain link for construction sites", "Ornamental at new-build entries", "School and park perimeters"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Coquitlam regulates fences under Zoning Bylaw No. 3000. Fences within standard height limits don't require a permit; taller acoustic or security fences along arterials often do, and creek and watercourse setbacks apply on many hillside lots.",
    bylawUrl: "https://www.coquitlam.ca/1073/Fences",
    bylawUrlLabel: "City of Coquitlam — Fences page",
    materialNotes: "Coquitlam's rain totals and shaded, north-facing slopes push a lot of cedar into premature moss and rot — we recommend an oil or stain within the first year, then every 3–5 years after.",
    uniqueParagraphs: [
      "Coquitlam is where slope work really tests a fencing crew. Burke Mountain and Westwood Plateau lots regularly drop 8–15 feet across the width of a standard yard, which means every fence is a stepped design and every post on the downhill side needs an extra foot of depth. We've built fences on Coquitlam hillsides where the top of the fence at the property line is 12 feet above the neighbour's grade — those runs need geotechnical judgment as much as fencing skill, and we'll bring in an engineer for retaining walls above 1.2 metres exposed. On the upside, once a hillside fence is properly stepped and set, the grade actually reduces wind load on any given panel because the fence is broken into shorter runs.",
      "The other Coquitlam constant is water. 1,700 mm of rain a year, dense tree cover on the north-facing lots, and creek corridors running through half the older neighbourhoods. Watercourse setback rules are enforced — you cannot fence into a Coquitlam riparian area — and cedar left unfinished on a shaded lot will grow moss within a year. On any shaded or north-facing Coquitlam job we recommend an oil or stain within twelve months and a re-coat every three to five years. Black vinyl-coated chain link is a common alternative here because it holds up in shade without any of the biological growth issues cedar has.",
    ],
    costNote: "Coquitlam pricing is comparable to Burnaby, with a 10–20% premium on the steep Burke Mountain and Westwood Plateau lots for the extra stepping, deeper posts, and access work.",
    faq: [
      { q: "Do I need a permit for a fence in Coquitlam?", a: "No permit for standard-height residential fences (1.83 m rear/side, 1.2 m front). Taller acoustic fences along arterials, watercourse-adjacent fences, and retaining walls over 1.2 m exposed height often require review." },
      { q: "Can I fence near a creek or watercourse in Coquitlam?", a: "Riparian setback rules apply on any Coquitlam property with a creek, ditch, or watercourse. We check the setback distance with the city before quoting fences that come within a few metres of any moving water." },
      { q: "How do you build a fence on a steep Burke Mountain lot?", a: "We step the fence in 4 or 6 foot sections to follow the grade rather than racking boards at an angle. Downhill posts are set deeper to compensate for the taller exposed span. On very steep grades we may recommend a small retaining wall at the base first." },
      { q: "What material lasts longest in Coquitlam's shaded, wet climate?", a: "Black vinyl-coated chain link outlasts cedar in constantly shaded and wet Coquitlam yards. If you want cedar for privacy, oil or stain within the first year and re-coat every 3–5 years to keep moss and rot at bay." },
      { q: "How much does a stepped hillside fence cost in Coquitlam?", a: "Expect a 10–20% premium over a comparable flat-lot install. A stepped 6-ft cedar privacy fence typically runs $70–$100 per linear foot on Coquitlam hillside lots, versus $60–$85 on flat ground." },
    ],
    ogImage: OG.wood,
  },
  {
    slug: "port-coquitlam",
    name: "Port Coquitlam",
    region: "Metro Vancouver",
    postalPrefix: "V3B / V3C",
    climate: "Port Coquitlam averages 1,600 mm of rain a year, similar to Coquitlam, with occasional flooding pressure near the Pitt and Coquitlam river confluences.",
    terrain: "PoCo is mostly flat river-plain land with some hillside neighbourhoods rising to the north — much easier to work than Coquitlam or Port Moody proper.",
    neighbourhoods: ["Downtown Port Coquitlam", "Central PoCo", "Lincoln Park", "Riverwood", "Citadel Heights", "Oxford Heights"],
    commonProjects: ["Cedar rear-yard privacy", "Chain link for construction fencing", "Fence line replacement on established streets", "Dog runs and pool enclosures"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Port Coquitlam regulates fences through its Zoning Bylaw. Fences within standard height limits don't require a permit; corner lot sightline rules and pool enclosure standards apply.",
    bylawUrl: "https://www.portcoquitlam.ca/city-hall/bylaws-policies/",
    bylawUrlLabel: "City of Port Coquitlam — Bylaws & policies",
    materialNotes: "Flat river-plain lots in Port Coquitlam are straightforward to fence — the main watch-out is the water table near the rivers, where posts benefit from a deeper set and dry-mix concrete.",
    uniqueParagraphs: [
      "Port Coquitlam is one of the easier cities in our territory to build fencing in — the ground is mostly flat, lots are a manageable size, and city bylaws follow the standard Metro Vancouver template without a lot of exotic add-ons. Our typical PoCo job is a straightforward 6-foot cedar rear-yard privacy fence with black vinyl-coated chain link down the side yard, installed in one to two days start to finish. Neighbourhoods like Lincoln Park, Oxford Heights, and Riverwood are full of established streets where the existing fence lines are 20–30 years old and everyone on the block is quietly waiting for their neighbour to replace first.",
      "The one PoCo constant to design around is proximity to the Coquitlam and Pitt rivers. Lots near the water have a higher water table than the flat blocks further from the rivers, and the freeze-thaw wobble on a shallow post is real. We default to 36-inch post depth on any Port Coquitlam job within about a kilometre of the rivers, use dry-mix bagged concrete that cures with the groundwater, and always crown the concrete top so water sheds off the post rather than pooling against it. That single detail — a proper concrete crown — probably adds five years to the life of a Port Coquitlam fence at basically zero material cost.",
    ],
    costNote: "Port Coquitlam sits at the median of our pricing — no urban access surcharge, no steep-slope premium, and no rocky-terrain problems. Straightforward flat-lot installs price as advertised.",
    faq: [
      { q: "Do I need a permit for a fence in Port Coquitlam?", a: "No permit for standard-height residential fences (1.83 m rear/side, 1.2 m front). Corner sightline triangles apply at intersections. Pool enclosures follow the BC Building Code." },
      { q: "How long does a fence install take in Port Coquitlam?", a: "A standard 100-foot residential run in Port Coquitlam is a one to two day job — day one for post holes and setting, day two for framing, boards, and gates. Longer runs or heavy gate work extend from there." },
      { q: "What's the best fence material for a Port Coquitlam backyard?", a: "Western red cedar for privacy, black vinyl-coated chain link for containment. Both handle PoCo's wet winters and mild summers well. Avoid pressure-treated fence boards — they twist and check faster than cedar in this climate." },
      { q: "Do you install pool enclosure fencing in Port Coquitlam?", a: "Yes. Pool enclosures in PoCo follow BC Building Code Part 9 — minimum 4-ft height, no climbable horizontal rails, and self-closing self-latching gates. We install ornamental steel picket and vinyl-coated chain link pool enclosures regularly." },
      { q: "How much does a cedar privacy fence cost in Port Coquitlam?", a: "$55–$85 per linear foot installed for a standard 6-ft cedar privacy fence in Port Coquitlam. Horizontal-slat modern styles run $85–$120 per linear foot. Gates price separately based on hardware and span." },
    ],
    ogImage: OG.best,
  },
  {
    slug: "port-moody",
    name: "Port Moody",
    region: "Metro Vancouver",
    postalPrefix: "V3H",
    climate: "Port Moody averages 2,000+ mm of rain — the wettest city in our territory — with heavy shade cover on north-facing slopes and low-lying inlet moisture.",
    terrain: "Port Moody wraps around Burrard Inlet with steep hillsides north and south of the water, plus flat lowland near Rocky Point and the Barnet Highway corridor.",
    neighbourhoods: ["Heritage Mountain", "Heritage Woods", "College Park", "Glenayre", "Ioco", "Anmore border", "Downtown Port Moody"],
    commonProjects: ["Cedar with premium finish for shaded lots", "Chain link on Heritage Mountain acreage", "Ornamental at Suter Brook and Newport Village", "Waterfront pool enclosures"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Port Moody follows a standard Metro Vancouver height envelope under its Zoning Bylaw. Steep-slope, tree-protection, and watercourse rules are more actively enforced here than in most Tri-Cities municipalities.",
    bylawUrl: "https://www.portmoody.ca/en/city-services/building-inspection-services.aspx",
    bylawUrlLabel: "City of Port Moody — Building & inspection services",
    materialNotes: "Port Moody's shade, rainfall, and inlet moisture are hard on any softwood fence — cedar needs finishing early and often, or we recommend vinyl-coated chain link where privacy matters less than durability.",
    uniqueParagraphs: [
      "Port Moody is the wettest city in our territory and it changes the way we spec every job. 2,000+ mm of rain a year, dense tree cover on Heritage Mountain and Heritage Woods, and constant inlet moisture through the winter combine to make it the toughest place in the Lower Mainland to keep a cedar fence looking good. We insist on an oil or stain within the first year on every Port Moody cedar install, and we're upfront with clients that the maintenance cycle here is shorter than anywhere else — expect a re-coat every three years, not five. Skip that step and moss will be established on the boards by year two.",
      "The other Port Moody watch-out is tree protection. The city takes its urban canopy seriously and there are specific bylaw rules around digging within the drip line of protected trees on private property. On several Heritage Mountain jobs we've adjusted the fence line inward by a foot or shifted a corner post to avoid an arborist consultation, because the alternative is a stop-work order the moment a neighbour reports the dig. On the plus side, Port Moody's higher-end neighbourhoods — Heritage Mountain, Heritage Woods, and the Suter Brook / Newport Village corridor — are strong candidates for ornamental steel front-yard fencing, which lasts indefinitely regardless of how much it rains.",
    ],
    costNote: "Port Moody pricing runs slightly above the Metro Vancouver average because of terrain, tree-protection watchouts, and the shorter finish-maintenance cycle we recommend on cedar.",
    faq: [
      { q: "Why does cedar need more maintenance in Port Moody?", a: "Port Moody averages 2,000+ mm of rain a year with heavy tree shade, especially on Heritage Mountain and Heritage Woods lots. That combination grows moss and greys cedar faster than anywhere else in our territory. Plan for a re-coat every 3 years instead of the usual 5." },
      { q: "Are there tree-protection rules that affect fence installs in Port Moody?", a: "Yes. Port Moody's tree bylaw restricts digging within the drip line of protected trees on private property. On lots with mature protected trees we may need to adjust the fence line or bring in an arborist before digging." },
      { q: "Do I need a permit for a fence in Port Moody?", a: "Not for a standard-height residential fence (1.83 m rear/side, 1.2 m front). Watercourse setbacks, retaining walls over 1.2 m exposed, and tree-protection zones can all trigger additional review." },
      { q: "What material lasts best in Port Moody's climate?", a: "Ornamental steel picket for front yards and vinyl-coated chain link for rear and side yards outlast cedar in Port Moody's shade and rainfall. Where cedar is chosen for privacy, budget for finishing on day one and every three years after." },
      { q: "How much does a Heritage Mountain fence install cost?", a: "Sloped, shaded Heritage Mountain lots typically add 10–20% over a flat-ground install. Expect $70–$105 per linear foot for a stepped 6-ft cedar privacy fence, plus finishing." },
    ],
    ogImage: OG.wood,
  },
  {
    slug: "langley",
    name: "Langley",
    region: "Metro Vancouver",
    postalPrefix: "V1M / V2Y / V2Z / V3A / V4W",
    climate: "Langley sits in the drier eastern Fraser Valley — 1,300 mm of rain a year, hotter summers than the coastal cities, and colder winter nights with more freeze-thaw.",
    terrain: "Langley spans dense residential in the City of Langley plus large agricultural and acreage properties across the Township — from Willoughby to Aldergrove.",
    neighbourhoods: ["Willoughby", "Walnut Grove", "Fort Langley", "Murrayville", "Brookswood", "Aldergrove", "Downtown Langley City"],
    commonProjects: ["Acreage perimeter chain link", "Farm and equestrian fencing", "New-build cedar in Willoughby", "Custom cantilever gates for commercial yards"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "The Township and City of Langley both follow a standard height envelope for residential fences without a permit. Agricultural (ALR) properties allow taller and different types of fencing for livestock containment.",
    bylawUrl: "https://www.tol.ca/en/home-property/fences.aspx",
    bylawUrlLabel: "Township of Langley — Fences",
    materialNotes: "Langley's mix of tight new-build lots and open acreage means we spec everything from clear-cedar horizontal-slat to 400-foot runs of galvanized page-wire — we regularly do both in the same week.",
    uniqueParagraphs: [
      "Langley is where our Fraser Valley volume really lives. We've been installing fencing across the Township and City of Langley for years, and it's the market where the widest possible spread of jobs shows up — a Willoughby new-build owner wanting a modern horizontal-slat clear-cedar privacy fence, a Brookswood family with two horses and 800 feet of pasture to enclose, an Aldergrove commercial building with a cantilever slide gate and barbed wire. That range is one of the reasons we invested in our own excavation kit and in-house welding shop, because outsourcing either would slow every one of those job types down.",
      "The Willoughby build-out over the last decade is the single biggest driver of new-fence demand in Langley. Row after row of new duplexes and townhomes hit occupancy and immediately need side-yard and rear-yard fencing. Our standard Willoughby package is 6-foot cedar rear yards on treated posts with galvanized post hardware, black vinyl-coated chain link side yards to keep sightlines open into the neighbour's yard, and a matching cedar gate at the side-yard entry. Fort Langley and Murrayville, on the other hand, are established residential streets where most of our work is replacement of existing 25-year-old cedar fences that have hit the end of their service life.",
    ],
    costNote: "Langley pricing is at or slightly below the Metro Vancouver average — access is easy, terrain is mostly flat, and longer acreage runs earn a per-linear-foot discount at 500+ feet.",
    faq: [
      { q: "Do I need a permit for a fence in Langley?", a: "No permit for standard-height residential fences (1.83 m rear/side, 1.2 m front) in either the Township or City of Langley. Agricultural properties have different rules; anything taller than the standard envelope requires a variance." },
      { q: "How much does farm fencing cost in Langley?", a: "5-ft page-wire farm fence with treated posts typically runs $12–$22 per linear foot installed in Langley. High-tensile electric and equestrian board fencing price separately based on wire spec and gate count." },
      { q: "Can you install fencing in Willoughby new-builds before landscaping is finished?", a: "Yes. We regularly coordinate with builders and landscapers in Willoughby to sequence the fence install right after grade is finished, so landscaping and irrigation can work around the completed fence line rather than the other way around." },
      { q: "Do you build equestrian fencing in Langley?", a: "Yes. Board fencing, high-tensile electric, page wire on treated posts, and combinations with gates and cattle guards for entry — we handle equestrian and small-livestock fencing across Brookswood, Aldergrove, and rural Langley regularly." },
      { q: "How long does it take to fence a Langley acreage?", a: "A 500-foot perimeter of chain link or page-wire farm fence on flat Langley acreage is typically a 3–5 day job, depending on gate count, terrain, and post spec. We give a written per-day schedule with every acreage quote." },
    ],
    ogImage: OG.best,
  },
  {
    slug: "delta",
    name: "Delta",
    region: "Metro Vancouver",
    postalPrefix: "V4C / V4E / V4G / V4K / V4L / V4M",
    climate: "Delta shares Richmond's coastal delta climate but sees more wind exposure at Tsawwassen and Boundary Bay — 1,100 mm of rain, marine salt on the coast, and open exposure to southwesterly winds.",
    terrain: "Delta is another river delta municipality with soft alluvial soil, a high water table, and dyke-protected agricultural land through Ladner and East Delta.",
    neighbourhoods: ["Tsawwassen", "Ladner Village", "Sunshine Hills", "North Delta", "Boundary Bay", "East Delta farmland"],
    commonProjects: ["Wind-rated cedar for Tsawwassen and Boundary Bay", "Farm fencing across East Delta ALR", "Cantilever gates for Tilbury industrial", "Pool enclosures near the water"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Delta regulates fencing under its Zoning Bylaw. Fences within standard height limits do not require a permit. Agricultural, industrial, and dyke-adjacent lots have their own requirements.",
    bylawUrl: "https://www.delta.ca/services/building-permits-inspections",
    bylawUrlLabel: "City of Delta — Building permits & inspections",
    materialNotes: "Delta's coastal wind exposure means we always spec three rails instead of two on any run over 5 ft, and hot-dip galvanized hardware end to end — the same salt-air rules that apply in Steveston apply here.",
    uniqueParagraphs: [
      "Delta is really three fencing markets on one map. Tsawwassen and Boundary Bay are wind-exposed coastal residential where every panel takes a load off the open water and every hardware bolt has to fight salt. Ladner is village-style residential with a mix of established fence lines and newer townhome development. East Delta is ALR farmland where the requirement isn't privacy or aesthetics — it's containment of cattle, horses, or equipment across long runs of open ground. We treat each of those as its own quoting exercise, and we always spec three rails instead of two on Tsawwassen and Boundary Bay cedar runs because a coastal southwesterly on an under-framed 6-foot cedar panel will find any weakness fast.",
      "The Tilbury industrial area on the east side of Delta is our commercial hub in this city. Warehouse tenants and marine-adjacent industrial operations there need serious perimeter security — 8-foot galvanized chain link with barbed wire and cantilever slide gates sized for a semi. We fabricate the cantilever gates in our own shop, which cuts weeks off the delivery time compared to sourcing them from a wholesaler. And unlike some contractors we can weld on-site if a gate needs modification after install, which matters on a working industrial yard where you can't wait for a shop return trip.",
    ],
    costNote: "Delta pricing is comparable to Surrey and Langley for inland residential; Tsawwassen and Boundary Bay coastal jobs run 5–10% higher for upgraded hardware and rail count.",
    faq: [
      { q: "Do I need a permit for a fence in Delta?", a: "No permit for a standard-height residential fence (1.83 m rear/side, 1.2 m front). Agricultural properties, industrial zones, and dyke-adjacent lots have additional requirements — we check before quoting." },
      { q: "Why do you spec three rails on a Tsawwassen fence?", a: "Tsawwassen and Boundary Bay take direct southwesterly wind off the water. A standard two-rail 6-ft cedar fence flexes and eventually fails at the middle. A third mid-rail transfers that wind load into the posts and dramatically extends the life of the fence." },
      { q: "Can you install cantilever slide gates in the Tilbury industrial area?", a: "Yes. Cantilever gates are one of our specialties — we fabricate the frame in our own shop in-house, install and align on-site, and can tie into keypad, card-reader, or LTE gate operators for access control. Tilbury and East Delta industrial are regular clients." },
      { q: "What's the best fence for a Ladner backyard?", a: "6-ft Western red cedar on treated posts with hot-dip galvanized hardware is the Ladner default. On lots close to the Fraser River or the dyke, we recommend 36-inch post depth to handle the higher water table." },
      { q: "Do you install ALR farm fencing in East Delta?", a: "Yes. Page-wire, high-tensile, and standard chain link for livestock and equipment containment across East Delta ALR properties. Long runs earn a per-foot discount." },
    ],
    ogImage: OG.gates,
  },
  {
    slug: "maple-ridge",
    name: "Maple Ridge",
    region: "Metro Vancouver",
    postalPrefix: "V2W / V2X / V4R",
    climate: "Maple Ridge averages 1,900 mm of rain — very wet — with more snow at elevation on the Silver Valley bench and Golden Ears foothills.",
    terrain: "Maple Ridge runs from flat river-plain along the Fraser up to steep, treed acreage in Silver Valley, Yennadon, and the Golden Ears foothills.",
    neighbourhoods: ["Silver Valley", "Albion", "Yennadon", "Hammond", "Whonnock", "Downtown Maple Ridge", "Websters Corners"],
    commonProjects: ["Acreage chain link with barbed wire", "Cedar and horizontal-slat privacy on new-builds", "Handrails and welded gates", "Log-yard and equipment perimeters"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Maple Ridge regulates fences under its Zoning Bylaw. Fences within standard heights don't require a permit; agricultural land, watercourse setbacks, and Wildland-Urban Interface areas may add requirements.",
    bylawUrl: "https://www.mapleridge.ca/1810/Fences",
    bylawUrlLabel: "City of Maple Ridge — Fences",
    materialNotes: "Maple Ridge's wet, treed environment is tough on cedar unless finished early; the flip side is that established rural fence lines run for hundreds of feet and reward well-set galvanized chain link.",
    uniqueParagraphs: [
      "Maple Ridge is one of our home markets. Between the log yards, working farms, hillside acreages, and steady stream of Silver Valley new-builds, we've probably installed more linear feet of fence in Maple Ridge than any single city outside Chilliwack and Abbotsford. The mix here is unusual — a Silver Valley homeowner wanting a horizontal-slat modern cedar fence in the morning, an acreage owner in Whonnock needing a 600-foot perimeter of galvanized chain link with barbed wire the same afternoon. Our welding shop is set up to fabricate handrails, driveway gates, and equipment-yard cantilever gates in-house, which is often the difference between a two-week and a six-week delivery on custom metalwork.",
      "Rain and tree cover are the two big design constraints. Silver Valley, Yennadon, and Websters Corners all sit on lots with mature Douglas-fir and cedar cover, which means shade, moss, and constant moisture at ground level. On those lots we spec 36-inch post depth as a default, always crown the concrete tops, and are upfront that any cedar fence in that environment needs an oil or stain within the first year. On the flip side, Hammond and Albion sit on flatter, more open ground closer to the river, and standard 30-inch post depth with two-rail construction works fine. We adjust the spec based on where the property actually sits, not on a one-size-fits-all Maple Ridge template.",
    ],
    costNote: "Maple Ridge pricing is in line with the Fraser Valley average — flat lots price standard, steep or heavily treed Silver Valley acreages run 10–15% higher for the extra dig work and post depth.",
    faq: [
      { q: "Do I need a permit for a fence in Maple Ridge?", a: "No permit for standard-height residential fences (1.83 m rear/side, 1.2 m front). Watercourse setbacks and Wildland-Urban Interface rules may add requirements on some acreages." },
      { q: "How long does a Maple Ridge acreage perimeter take to install?", a: "A 500-foot perimeter of 6-ft galvanized chain link with barbed wire on flat Maple Ridge acreage is typically a 3–5 day job depending on gate count and terrain. Wooded or steep sites take longer." },
      { q: "Can you weld custom driveway gates for a Maple Ridge property?", a: "Yes. We fabricate custom swing and cantilever driveway gates in our own welding shop, install on-site, and can tie into keypad or LTE gate operators. Turnaround is typically 2–3 weeks from approved drawings." },
      { q: "What material holds up best on a Silver Valley wooded lot?", a: "Black vinyl-coated chain link outlasts cedar in constantly shaded, wet Silver Valley conditions. If you want cedar for privacy, oil or stain within the first year and re-coat every 3 years." },
      { q: "How much does a fence cost in Maple Ridge?", a: "$55–$85 per linear foot for a 6-ft cedar privacy fence, $32–$48 for galvanized chain link, $42–$60 for black vinyl-coated chain link. Sloped or heavily treed Silver Valley lots add 10–15%." },
    ],
    ogImage: OG.wood,
  },
  {
    slug: "pitt-meadows",
    name: "Pitt Meadows",
    region: "Metro Vancouver",
    postalPrefix: "V3Y",
    climate: "Pitt Meadows sits on the Fraser and Pitt river floodplain — 1,600 mm of rain a year, high water table, and significant summer humidity.",
    terrain: "Pitt Meadows is almost entirely flat river-plain agricultural land, with a compact residential core near the town centre and dyke-protected farmland covering most of the municipality.",
    neighbourhoods: ["Downtown Pitt Meadows", "Bonson", "Central Meadows", "North Pitt Meadows", "Osprey Village", "Rural Pitt Meadows"],
    commonProjects: ["ALR farm perimeter fencing", "Cedar privacy in Bonson and Osprey Village", "Equestrian board fencing", "Dyke-adjacent chain link"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Pitt Meadows follows a standard height envelope for residential fences. Agricultural (ALR) properties allow taller and different fencing for livestock. Dyke setbacks are enforced.",
    bylawUrl: "https://www.pittmeadows.ca/en/business-and-development/building-permits-and-inspections.aspx",
    bylawUrlLabel: "City of Pitt Meadows — Building permits & inspections",
    materialNotes: "Pitt Meadows' high water table and mostly agricultural land mean the majority of our work here is on treated posts set to 36 inches or deeper, with page-wire, high-tensile, or chain link mesh depending on use.",
    uniqueParagraphs: [
      "Pitt Meadows is one of the most rural municipalities in Metro Vancouver, and that shapes almost every fencing job we do here. Working farms, equestrian properties, blueberry fields, and the Pitt Polder acreages all have containment needs that look nothing like a Vancouver rear yard. Our typical Pitt Meadows quote is 300 to 800 linear feet of 5-foot page-wire farm fence on treated posts, or standard 6-foot galvanized chain link for equipment-yard perimeters, with driveway gates sized to allow a tractor and trailer through. We factor a per-foot discount into any Pitt Meadows run over 500 feet because the setup and mobilization cost gets amortized across a bigger job.",
      "The residential half of Pitt Meadows — Bonson, Osprey Village, and the newer subdivisions in Central Meadows — is small enough that most homeowners already know their neighbours, which usually makes shared-fence conversations easier than in a big-city context. Standard spec is 6-foot cedar rear yards with black vinyl-coated chain link side yards, on treated posts set to 36 inches because the water table is high year-round. We use dry-mix bagged concrete tipped into the wet hole, which lets the groundwater hydrate it rather than fighting to keep the hole dry — a small trick that saves a lot of time on Pitt Meadows installs.",
    ],
    costNote: "Pitt Meadows pricing is competitive on any acreage or long-run job because setup gets amortized over more linear feet. Small residential quotes price at the Fraser Valley standard.",
    faq: [
      { q: "Do you install farm fencing in Pitt Meadows?", a: "Yes. Page-wire on treated posts, high-tensile electric, and standard chain link for livestock and equipment containment across ALR properties in Pitt Meadows. Longer runs earn a per-foot discount." },
      { q: "Do I need a permit for a fence in Pitt Meadows?", a: "No permit for standard-height residential fences (1.83 m rear/side, 1.2 m front). Agricultural properties have different rules; dyke setback distances apply on any property backing onto the dyke system." },
      { q: "Why do you set posts deeper in Pitt Meadows?", a: "The water table across most of Pitt Meadows is within a few feet of the surface year-round. Standard 30-inch post depth can walk out of soft, saturated ground over freeze-thaw cycles. We default to 36 inches on residential and 42 inches on gates." },
      { q: "Can you install equestrian fencing in Pitt Meadows?", a: "Yes. Board fencing, page wire on treated posts, high-tensile electric, and cross-fencing for paddock rotation. We coordinate with the property owner on gate placement and cattle-guard entries as needed." },
      { q: "How much does farm fencing cost in Pitt Meadows?", a: "$12–$22 per linear foot for 5-ft page-wire on treated posts, depending on terrain and gate count. Chain link on farm properties runs $28–$44 per linear foot. Longer runs (500+ ft) earn a per-foot discount." },
    ],
    ogImage: OG.best,
  },
  {
    slug: "new-westminster",
    name: "New Westminster",
    region: "Metro Vancouver",
    postalPrefix: "V3L / V3M",
    climate: "New Westminster shares Metro Vancouver's coastal climate — 1,200 mm of rain a year, mild winters, and morning fog off the Fraser River.",
    terrain: "New West is defined by its slope — the entire city runs from the Fraser River waterfront up through Queens Park, Sapperton, and the West End at a consistent grade.",
    neighbourhoods: ["Queens Park", "Sapperton", "West End New West", "Brow of the Hill", "Uptown", "Queensborough", "Glenbrooke North"],
    commonProjects: ["Heritage-style cedar in Queens Park", "Chain link for construction and commercial sites", "Ornamental steel at premium properties", "Retaining-wall fences on the slope"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "New Westminster regulates fences under its Zoning Bylaw. Fences within standard height limits don't require a permit. Heritage-designated properties in Queens Park have additional design guidelines.",
    bylawUrl: "https://www.newwestcity.ca/services/building-permits-and-inspections",
    bylawUrlLabel: "City of New Westminster — Building permits & inspections",
    materialNotes: "New Westminster's older housing stock and heritage areas push a lot of picket-style cedar and ornamental steel, especially in and around Queens Park — a nod to the city's Victorian era streetscapes.",
    uniqueParagraphs: [
      "New Westminster is one of the oldest cities in BC and it shows in the fencing work. Queens Park in particular is a heritage neighbourhood full of century homes on original lot lines, and the fence style expectations there lean strongly toward classic cedar picket, ornamental steel, and horizontal or vertical board with a decorative top cap — not the plain 6-foot dog-eared cedar you'd see in a Fleetwood cul-de-sac. We've built enough Queens Park fences to know the neighbourhood aesthetic norms, and where a property is heritage-designated we check the current design guidelines before quoting anything.",
      "The slope from the Fraser River waterfront up to the West End of New West runs through basically every job we do here. Consistent grade change means every fence is a stepped design, and posts on the downhill side need extra depth. Sapperton and the Brow of the Hill have some of the steepest residential lots in the city, and we've done a fair bit of retaining-wall fence integration work in those neighbourhoods — where a low engineered retaining wall handles the grade change and a standard cedar fence sits on top. Queensborough, on the other hand, is flat delta land and behaves more like Richmond — deeper posts, water table considerations, and the same salt-tolerant hardware spec.",
    ],
    costNote: "New West pricing runs slightly above the Metro Vancouver average because most jobs involve stepping for slope, and Queens Park heritage work often calls for premium picket or ornamental spec that costs more per foot.",
    faq: [
      { q: "Do I need a permit for a fence in New Westminster?", a: "No permit for standard-height residential fences (1.83 m rear/side, 1.2 m front). Heritage-designated properties, particularly in Queens Park, may have additional design review requirements — check with the city before finalizing style." },
      { q: "Can you match a heritage fence style in Queens Park?", a: "Yes. Queens Park's heritage streetscapes call for cedar picket, ornamental steel, and traditional board-and-batten styles rather than plain dog-eared cedar. We build to match the neighbourhood aesthetic and, on designated properties, to city design guidelines." },
      { q: "How do you handle sloped fences in Sapperton or the Brow of the Hill?", a: "We step the fence in 4 or 6 foot sections to follow the grade cleanly, with deeper post-hole depth on the downhill side. On very steep lots we may recommend a low engineered retaining wall at the base with the cedar fence on top." },
      { q: "What's the cost of a cedar picket fence in Queens Park?", a: "Traditional cedar picket (3–4 ft) with a decorative top cap runs $65–$95 per linear foot installed in Queens Park. Full-height (6-ft) heritage board-and-batten cedar runs $75–$110 per linear foot. Ornamental steel runs $95–$150." },
      { q: "Can you build a fence on a Queensborough lot?", a: "Yes. Queensborough is flat delta land like Richmond — high water table, softer soil, so we set posts to 36 inches minimum with hot-dip galvanized hardware to handle the wet conditions." },
    ],
    ogImage: OG.best,
  },
  {
    slug: "north-vancouver",
    name: "North Vancouver",
    region: "Metro Vancouver",
    postalPrefix: "V7G / V7H / V7J / V7K / V7L / V7M / V7N / V7P / V7R",
    climate: "North Vancouver gets 2,000+ mm of rain — one of the wettest cities in Canada — with heavy tree cover, mountainside shade, and higher elevation snow.",
    terrain: "The entire District and City of North Vancouver runs up the south face of the North Shore mountains, with almost every lot on some degree of slope.",
    neighbourhoods: ["Deep Cove", "Lynn Valley", "Edgemont Village", "Upper Lonsdale", "Central Lonsdale", "Blueridge", "Seymour"],
    commonProjects: ["Stepped cedar on steep hillside lots", "Chain link with premium finish for wet conditions", "Ornamental steel entry gates", "Retaining wall + fence combinations"],
    bylawHeight: "1.83 m rear/side, 1.2 m front (District & City)",
    bylawSummary: "Both the District and City of North Vancouver follow standard height envelopes for residential fences without a permit. Tree-protection bylaws, watercourse setbacks, and steep-slope development permits are more actively enforced here than most Metro Vancouver municipalities.",
    bylawUrl: "https://www.dnv.org/property-and-development/fences-and-retaining-walls",
    bylawUrlLabel: "District of North Vancouver — Fences & retaining walls",
    materialNotes: "The wet, shaded, sloped North Vancouver environment is genuinely difficult for cedar — we recommend committing to a finish maintenance schedule day one, or defaulting to ornamental steel and vinyl-coated chain link for lower-maintenance runs.",
    uniqueParagraphs: [
      "North Vancouver is the toughest fencing environment in our territory. 2,000+ mm of rain a year, dense evergreen tree cover on almost every lot, near-permanent shade on north-facing slopes, and grades so steep that some Deep Cove and Blueridge properties drop 20 feet across the width of a standard yard. On those lots we step the fence aggressively, set downhill posts to 42 inches, and are direct with clients about the finish maintenance a cedar fence will need — oil or stain within the first year, re-coat every 3 years, and expect a full replacement in year 20 rather than year 25. Skipping any of that gets you moss and grey boards inside two winters.",
      "Tree protection is the other major constraint. The District of North Vancouver protects mature trees on private property with specific rules about digging within the drip line, and violations get flagged fast by neighbours. On several Lynn Valley and Edgemont jobs we've shifted a fence line inward by a foot or repositioned a corner to avoid an arborist consultation. On the upside, North Vancouver's high-end neighbourhoods — Upper Lonsdale, Edgemont, and Deep Cove — are strong candidates for ornamental steel entry gates and picket, which are essentially maintenance-free and hold up indefinitely in the coastal climate.",
    ],
    costNote: "North Vancouver pricing runs 10–20% above the Metro Vancouver average because of terrain, tree-protection work, deeper posts, and the finish-maintenance conversation on any cedar job.",
    faq: [
      { q: "Do I need a permit for a fence in North Vancouver?", a: "Not for a standard-height residential fence (1.83 m rear/side, 1.2 m front) in either the District or City of North Vancouver. Steep-slope development permits, watercourse setbacks, and tree-protection zones can all add requirements." },
      { q: "How do you build a fence on a steep Deep Cove or Blueridge lot?", a: "We step the fence in 4 or 6 foot sections rather than racking boards at an angle. Downhill posts are set to 42 inches for stability. On very steep grades we may recommend an engineered retaining wall at the base first." },
      { q: "Are there tree-protection rules that affect fence installs in North Vancouver?", a: "Yes. The District of North Vancouver protects mature trees on private property. Digging within a protected tree's drip line may require an arborist consultation. We check for protected trees before quoting." },
      { q: "What material lasts longest in North Vancouver's wet climate?", a: "Ornamental steel picket and vinyl-coated chain link outlast cedar significantly in North Vancouver's shade and rainfall. Cedar remains popular for privacy but needs early and regular finishing to last." },
      { q: "How much does a stepped hillside fence cost in North Vancouver?", a: "Expect a 15–20% premium over a comparable flat-lot install. Stepped 6-ft cedar privacy fence typically runs $75–$110 per linear foot in North Vancouver, plus finishing." },
    ],
    ogImage: OG.wood,
  },
  {
    slug: "west-vancouver",
    name: "West Vancouver",
    region: "Metro Vancouver",
    postalPrefix: "V7S / V7T / V7V / V7W",
    climate: "West Vancouver averages 1,900 mm of rain, with heavy tree cover, mountainside shade, and pronounced elevation change from Ambleside up to the British Properties.",
    terrain: "West Vancouver is almost entirely mountainside — steep, rocky, and often on lots with view protection covenants that affect fence height.",
    neighbourhoods: ["Ambleside", "Dundarave", "British Properties", "Caulfeild", "Cypress Park", "Horseshoe Bay", "Whytecliff"],
    commonProjects: ["Ornamental steel entry gates", "Stepped cedar on view-protected lots", "Custom cantilever driveway gates", "Handrails and metalwork on stone walls"],
    bylawHeight: "Typically 0.9–1.2 m front, 1.83 m rear (view corridors may reduce further)",
    bylawSummary: "West Vancouver's fence rules are stricter than most Metro Vancouver cities to protect view corridors. Front-yard fences are often capped lower than the regional standard, and view-covenanted lots may require even shorter fences.",
    bylawUrl: "https://westvancouver.ca/home-building-property/permits-inspections",
    bylawUrlLabel: "District of West Vancouver — Permits & inspections",
    materialNotes: "West Vancouver's premium residential market and view-protection rules push us toward ornamental steel, custom welded gates, and shorter fence heights that maintain sightlines — cedar is more often the interior privacy fence than the street-facing one.",
    uniqueParagraphs: [
      "West Vancouver is a specialty market for us. The residential price point is the highest in Metro Vancouver, the design expectations are correspondingly higher, and the terrain — steep, rocky, view-covenanted — means almost every job needs custom fabrication rather than off-the-shelf spec. Our typical West Van job is a custom ornamental steel entry gate with matching side pedestrian gates, powder-coated in a colour chosen to complement the house, tied into a keypad or LTE gate operator. On the back side of the property we might install cedar or vinyl-coated chain link for privacy and containment, but the front-yard and driveway work is almost always ornamental.",
      "View protection is unique to West Vancouver in our territory. Many Ambleside, Dundarave, and British Properties lots have view corridor covenants registered on title that cap fence heights below the standard bylaw envelope. Before every West Van quote we check for view covenants, and where they exist we may design the fence with a solid base course and open picket top to preserve sightlines through the fence — a middle ground that protects both privacy and view. Rocky terrain in the British Properties and Caulfeild is the other constant, and we come to those jobs prepared with percussion drilling attachments on our excavator because a standard auger will not touch that ground.",
    ],
    costNote: "West Vancouver pricing runs meaningfully above the Metro Vancouver average — custom ornamental fabrication, rocky-terrain drilling, and view-covenant design work all add to the per-foot cost.",
    faq: [
      { q: "Do I need a permit for a fence in West Vancouver?", a: "West Vancouver's rules are stricter than most Metro Vancouver cities. Standard-height residential fences don't require a permit, but view corridor covenants on many lots cap fence height below the standard envelope. Always check for a view covenant before designing." },
      { q: "How tall can a front-yard fence be in West Vancouver?", a: "Typically 0.9–1.2 m in the front yard, sometimes less on view-covenanted lots. Rear-yard fences follow the regional 1.83 m standard, subject to view corridors and steep-slope development permits." },
      { q: "Can you build a fence on a rocky British Properties lot?", a: "Yes. We come to British Properties and Caulfeild jobs with percussion drilling attachments on our excavator specifically for the rocky terrain there. A standard auger won't touch that ground." },
      { q: "Do you fabricate custom ornamental gates in West Vancouver?", a: "Yes. Custom ornamental swing and cantilever driveway gates are one of our specialties. Powder-coated in a colour of choice, tied into keypad, card-reader, or LTE gate operators as needed. Turnaround is typically 3–4 weeks from approved drawings." },
      { q: "How much does a West Vancouver ornamental entry gate cost?", a: "Custom ornamental swing driveway gates in West Vancouver typically start around $6,500–$12,000+ depending on span, design complexity, automation, and integration with existing stone or masonry. Every gate is a written quote based on drawings." },
    ],
    ogImage: OG.gates,
  },
  {
    slug: "white-rock",
    name: "White Rock",
    region: "Metro Vancouver",
    postalPrefix: "V4B",
    climate: "White Rock enjoys some of the sunniest and driest weather in Metro Vancouver — 1,100 mm of rain — but sits directly on Semiahmoo Bay with constant marine exposure.",
    terrain: "White Rock is a compact hillside community sloping from a bluff down to the Semiahmoo Bay waterfront, with view corridors playing a major role in fence design.",
    neighbourhoods: ["West Beach", "East Beach", "Uptown White Rock", "Kent Street area", "Vidal Street", "The Hillside"],
    commonProjects: ["View-conscious ornamental fencing", "Coastal cedar with upgraded hardware", "Custom gates for premium hillside properties", "Chain link for larger lots"],
    bylawHeight: "1.83 m rear, 1.2 m front (view corridors may reduce)",
    bylawSummary: "White Rock regulates fences under its Zoning Bylaw. Standard height limits apply without a permit, but view corridor considerations and coastal setbacks affect many properties.",
    bylawUrl: "https://www.whiterockcity.ca/153/Bylaws",
    bylawUrlLabel: "City of White Rock — Bylaws",
    materialNotes: "White Rock's coastal exposure calls for hot-dip galvanized hardware end to end, and its view-conscious design culture pushes us toward ornamental steel and open-picket cedar rather than solid privacy panels facing the water.",
    uniqueParagraphs: [
      "White Rock is a small city with a distinct fencing culture. The bluff-to-beach slope, ocean views, and higher-end residential market mean most fence conversations here start with a view discussion. Solid 6-foot cedar privacy fences facing the water are rare — most clients want either an open ornamental picket, a solid base with picket top, or cedar horizontal-slat with intentional gaps that preserve sightlines through the fence. We've done a fair bit of ornamental steel with mesh infill in White Rock too, which gives you dog-and-child containment without blocking the view.",
      "The salt-air problem is real in White Rock. West Beach, East Beach, and the properties directly on Marine Drive take constant marine salt spray, and any hardware that isn't hot-dip galvanized or stainless will rust and bleed through boards inside two years. We spec stainless ring-shank nails on cedar and hot-dip galvanized screws on structural connections for every White Rock job within a few blocks of the water. Uphill of the hillside — Uptown and the Kent Street area — the salt exposure drops significantly, and standard hot-dip galvanized hardware performs well without needing the stainless upgrade.",
    ],
    costNote: "White Rock pricing runs slightly above the Metro Vancouver average for the upgraded hardware, custom ornamental fabrication, and view-conscious design work most jobs require.",
    faq: [
      { q: "Do I need a permit for a fence in White Rock?", a: "No permit for a standard-height residential fence. View corridors and coastal setbacks affect design on many White Rock lots — we check for covenants and neighbour view considerations before quoting." },
      { q: "How do you build a fence that doesn't block ocean views in White Rock?", a: "Common White Rock approaches are ornamental steel picket, cedar horizontal slat with intentional gaps, or a solid base course with an open picket top — all preserve sightlines through the fence while still providing containment for kids and dogs." },
      { q: "Why does the hardware matter more in White Rock?", a: "Constant marine salt spray on West Beach, East Beach, and Marine Drive properties will rust plain zinc-plated hardware within two years, staining the boards. We use stainless ring-shank nails and hot-dip galvanized screws on any coastal White Rock job." },
      { q: "Can you build custom driveway gates in White Rock?", a: "Yes. Custom ornamental swing gates fabricated in our own welding shop, powder-coated to match the property, and tied into keypad, card reader, or LTE gate operators as needed. Turnaround is 2–4 weeks depending on complexity." },
      { q: "How much does an ornamental fence cost in White Rock?", a: "Ornamental steel picket runs $95–$150 per linear foot installed in White Rock. Custom hybrid designs — steel with mesh infill, or steel over a cedar base — price on drawings. Coastal hardware upgrades add a small per-foot premium." },
    ],
    ogImage: OG.gates,
  },
  {
    slug: "mission",
    name: "Mission",
    region: "Fraser Valley",
    postalPrefix: "V2V / V4S",
    climate: "Mission averages 1,700 mm of rain a year, with hot summers, cold winter nights, and enough elevation change to see occasional snow at higher points.",
    terrain: "Mission runs from flat Fraser River flatland along the highway up steep bench land to the north — Silverdale, Cedar Valley, and the Hatzic bench.",
    neighbourhoods: ["Downtown Mission", "Cedar Valley", "Silverdale", "Hatzic", "Mission Village", "West Heights"],
    commonProjects: ["Acreage chain link with barbed wire", "Cedar privacy on new-build subdivisions", "Farm and equestrian fencing", "Custom driveway gates for hillside properties"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "Mission regulates fences under its Zoning Bylaw. Fences within standard height limits don't require a permit. Agricultural properties allow taller fencing for livestock; watercourse setbacks apply on many hillside lots.",
    bylawUrl: "https://www.mission.ca/departments/planning/",
    bylawUrlLabel: "District of Mission — Planning department",
    materialNotes: "Mission's mix of hillside acreage and flat river-plain residential means we bring both auger and percussion post drilling to most quotes — Cedar Valley and Silverdale often need percussion for rocky bench ground.",
    uniqueParagraphs: [
      "Mission has become a steady part of our Fraser Valley work over the last several years. New residential subdivisions in Cedar Valley and along West Heights have pulled a lot of demand for standard 6-foot cedar privacy fencing with black vinyl-coated chain link side yards, and the hillside acreage properties in Silverdale and Hatzic keep us in the acreage and farm fencing business here. The Silverdale bench in particular is rocky ground — we bring percussion drilling attachments to those jobs specifically, because a standard auger will spin uselessly on bedrock.",
      "The steep-slope pattern in Mission mirrors what we see in Coquitlam and North Vancouver — stepped fence designs, deeper downhill posts, and watercourse setbacks that can catch a homeowner by surprise. Cedar Valley in particular has several protected creeks and watercourses running through it, and we check the current setback requirements with the District of Mission before quoting any fence within a few metres of a watercourse. Downtown Mission and Mission Village are flatter and simpler — standard residential fencing spec, 30-inch post depth, two rails on 6-foot cedar and three rails on anything windier or over 6 feet.",
    ],
    costNote: "Mission pricing is at the Fraser Valley average for flat-lot residential work. Rocky Silverdale bench sites and stepped hillside runs add 10–15% for the extra drilling and dig time.",
    faq: [
      { q: "Do I need a permit for a fence in Mission?", a: "No permit for standard-height residential fences (1.83 m rear/side, 1.2 m front). Agricultural properties and watercourse-adjacent lots have additional requirements — we check with the District before quoting." },
      { q: "Can you install fencing on Silverdale's rocky ground?", a: "Yes. Silverdale's bench land is often rocky enough that a standard auger won't work. We bring percussion drilling attachments to those jobs specifically. It adds a small per-hole premium but ensures posts are set to proper depth." },
      { q: "How much does an acreage fence cost in Mission?", a: "5-ft page-wire farm fence runs $12–$22 per linear foot installed. 6-ft galvanized chain link with barbed wire for acreage security runs $32–$48 per linear foot. Long runs earn a per-foot discount at 500+ ft." },
      { q: "Can you build a custom driveway gate for a Mission property?", a: "Yes. Custom swing and cantilever driveway gates fabricated in our own welding shop, installed and aligned on-site, and tied into keypad or LTE gate operators. Turnaround is typically 2–3 weeks from approved drawings." },
      { q: "What's the best fence for Cedar Valley new-builds?", a: "Standard Cedar Valley new-build spec is 6-ft Western red cedar rear yards on treated posts, with black vinyl-coated chain link side yards to keep sightlines open and reduce maintenance. Front-yard picket or ornamental is optional and priced separately." },
    ],
    ogImage: OG.best,
  },
  {
    slug: "hope",
    name: "Hope",
    region: "Fraser Valley",
    postalPrefix: "V0X",
    climate: "Hope sits at the eastern edge of the Fraser Valley — the wet meets the dry — averaging 1,900 mm of rain with real winter snow accumulation and hot summer temperatures.",
    terrain: "Hope is mountain-enclosed river confluence country. Flat river-plain in town, steep forested slopes on all sides, and rocky ground almost everywhere off the flats.",
    neighbourhoods: ["Downtown Hope", "Silver Creek", "Kawkawa Lake", "Flood-Hope", "Coquihalla-side acreage", "Rural Hope"],
    commonProjects: ["Rural acreage perimeter chain link", "Log-yard and equipment enclosures", "Wildlife-resistant page wire", "Custom welded gates for forestry properties"],
    bylawHeight: "1.83 m rear/side, 1.2 m front",
    bylawSummary: "The District of Hope regulates fences through its Zoning Bylaw. Fences within standard heights don't require a permit; rural, agricultural, and industrial properties have different allowances.",
    bylawUrl: "https://hopebc.ca/business-development/building-permits-inspections/",
    bylawUrlLabel: "District of Hope — Building permits & inspections",
    materialNotes: "Hope's rocky ground makes percussion drilling mandatory on most rural jobs, and the wildlife pressure (deer, bear, occasional cougar) shifts spec toward taller and stronger perimeters than a Vancouver quote would call for.",
    uniqueParagraphs: [
      "Hope is the eastern boundary of our territory and it's genuinely different from the rest of the Fraser Valley. The town sits at the confluence of the Fraser and Coquihalla rivers, surrounded by mountains on three sides, with rocky ground almost everywhere off the flat river-plain in the town centre. We come to any Hope acreage job with our percussion drilling kit ready because a standard auger will not get to proper post depth in most rural Hope soil. Log yards, forestry equipment enclosures, and rural residential acreages make up most of our Hope work — the aesthetic-driven suburban fencing that dominates in Willoughby or Bonson is a small share of the market here.",
      "Wildlife is the other real Hope-specific consideration. Deer, bear, and — less commonly — cougar move through rural Hope properties regularly, and the standard 5-foot page-wire farm fence that works fine in Pitt Meadows is often not tall enough here. On acreage jobs where wildlife pressure is real, we'll spec 6- or 8-foot fencing, top strands of high-tensile wire, and gate hardware that a bear can't easily manipulate. The bylaw framework here is standard, but the practical spec is closer to what you'd see in an interior BC ranch install than what you'd expect from a Metro Vancouver suburban fence.",
    ],
    costNote: "Hope acreage pricing includes a mandatory percussion drilling premium on rocky sites and a small mobilization fee that reflects the additional travel time from our Chilliwack home base.",
    faq: [
      { q: "Do you install fencing in Hope?", a: "Yes. Hope is at the eastern edge of our territory. We install acreage, farm, industrial, and residential fencing throughout the District of Hope and rural surrounding areas — Silver Creek, Kawkawa Lake, and the Coquihalla-side properties included." },
      { q: "Do I need a permit for a fence in Hope?", a: "No permit for standard-height residential fences (1.83 m rear/side, 1.2 m front). Rural and agricultural properties have different allowances; industrial perimeters and any fence within a watercourse setback require additional review." },
      { q: "Why does Hope need percussion drilling for posts?", a: "Most rural Hope ground is rocky — standard augers spin uselessly on bedrock. We bring percussion drilling attachments on our excavator specifically for the rocky terrain around Hope, Silver Creek, and Kawkawa Lake." },
      { q: "How do you build a wildlife-resistant fence in Hope?", a: "For acreages with real wildlife pressure (deer, bear), we spec taller fencing than a suburban quote — 6 or 8 feet — with top strands of high-tensile wire and gate hardware that a bear can't easily manipulate. Fence design should match the specific wildlife you're managing." },
      { q: "How much does a Hope acreage fence cost?", a: "5-ft page-wire on treated posts runs $14–$26 per linear foot installed in Hope (higher end reflects rocky ground). 6-ft galvanized chain link runs $34–$52 per linear foot. Percussion drilling and mobilization to remote sites add to the base." },
    ],
    ogImage: OG.best,
  },
];
